TasksManager/urls.py
from django.contrib import admin
from django.urls import path, include
from TasksManager.settings import SITE_NAME

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.tasks.urls', namespace='tasks')),
]

admin.site.site_header = SITE_NAME
admin.site.site_title = SITE_NAME
admin.site.index_title = SITE_NAME

apps/tasks/urls.py
from django.urls import path, include
# import debug_toolbar
from apps.tasks import views, tests
from TasksManager import settings

app_name = 'tasks'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:year>/<int:month>/', views.IndexView.as_view(), name='index_month'),
    path('test/', tests.TestView.as_view(), name='test'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('todolist/', views.TodoListView.as_view(), name='todolist'),
    path('todolist/<int:year>/<int:month>/', views.TodoListView.as_view(), name='todolist_month'),
    path('group_todolist/', views.GroupTodoList.as_view(), name='group_todolist'),
    path('group_todolist/<int:year>/<int:month>/', views.GroupTodoList.as_view(), name='group_todolist_month'),
    path('todo/<int:pk>/', views.TodoEntryView.as_view(), name='todo_detail'),
    path('tasklist/', views.TaskListView.as_view(), name='tasklist'),
    path('tasklist/<int:year>/', views.TaskListView.as_view(), name='tasklist_year'),
    path('about/', views.AboutView.as_view(), name='about'),
]
#
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

apps/tasks/forms.py
from django import forms
from .models import Todo


class LoginForm(forms.Form):
    username = forms.CharField(error_messages={'required': '用户名不能为空'})
    password = forms.CharField()
    remember = forms.BooleanField(required=False)


# TODO 数据不可为空
class TodoForm(forms.ModelForm):
    required_css_class = 'required'

    # (confused by Form & ModelForm https://stackoverflow.com/questions/2303268/djangos-forms-form-vs-forms-modelform)
    # maturity = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control'}), choices=(
    #     ('0%', '0%'),
    #     ('10%', '10%'),
    #     ('50%', '50%'),
    #     ('90%', '90%'),
    #     ('100%', '100%')
    # ))
    # real_work = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    # sub_executor = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs={'class': 'form-control'}))

    class Meta:
        model = Todo
        fields = ['maturity', 'real_work', 'sub_executor', 'evaluate_factor', 'complete_note']
        widgets = {'complete_note': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
                   # 'evaluate_factor': forms.NumberInput(attrs={'class': 'form-control'}),
                   }

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)
        # self.fields['sub_executor'].widget.attrs['class'] = 'form-control'
        fields = ['maturity', 'real_work', 'sub_executor', 'evaluate_factor', 'complete_note']
        for i in fields:
            self.fields[i].widget.attrs['class'] = 'form-control'

apps/tasks/views.py
import re
from collections import defaultdict, Counter
from copy import deepcopy

from django.contrib import auth, messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, F, FloatField, Count, Q
from django.db.models.functions import Coalesce
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
import django.utils.timezone as timezone
from django.utils.http import url_has_allowed_host_and_scheme
from django.views import View
from django.db import connection
# Create your views here.
from apps.tasks.models import Todo, Task
from apps.tasks.forms import TodoForm
from apps.users.models import User
from . import my_query
from functools import reduce
import pandas as pd

import decimal


class IndexView(View):
    @method_decorator(login_required)
    def get(self, request, year=None, month=None):
        # 搞成了！！！ 当月份更改时自动变更首页显示的月份！ 其实就是用的上面那个链接的方法，之前不知道为啥没去用
        #  https://stackoverflow.com/questions/63072235/django-localdate-doesnt-return-correct-date
        #  https://stackoverflow.com/questions/13225890/django-default-timezone-now-saves-records-using-old-time
        #  https://stackoverflow.com/questions/38237777/django-timezone-now-vs-timezone-now
        if year is None:
            year = timezone.now().year
        if month is None:
            month = timezone.now().month
        #TODO 部门不用部门下用户累加
        # 建立username和真实姓名的对应字典，并在工作量计算完成后插入结果集
        user_info = User.objects.filter(department=request.user.department)\
            .values_list('username', 'real_name')
        user_name = {}
        for user in user_info:
            user_name[user[0]] = user[1]
        # print(user_name)

        # 以用户表查询，按用户列出所参与承办、协办任务，并在之后按用户名分组合并。
        main_credit = User.objects.filter(department=request.user.department,
                                          main_executor__deadline__year=year, main_executor__deadline__month=month)\
            .annotate(main_count=Count('main_executor'))\
            .order_by('username')\
            .values('username', 'main_executor', 'main_executor__predict_work', 'main_executor__real_work',
                    'main_executor__evaluate_factor', 'main_count')  # 这里的annotate不知会不会有问题

        sub_count = Todo.objects.filter(sub_executor__department=request.user.department,
                                        deadline__year=year, deadline__month=month) \
            .annotate(sub_count=Count('sub_executor')).values('id', 'sub_count')
        sub_credit = User.objects.filter(department=request.user.department,
                                         sub_executor__deadline__year=year, sub_executor__deadline__month=month) \
            .order_by('username') \
            .values('username', 'real_name', 'sub_executor', 'sub_executor__predict_work', 'sub_executor__real_work',
                    'sub_executor__evaluate_factor')

        # 构建工作包id对应协办人人数的字典
        sub_exe_count = {}
        for i in sub_count:
            key = i['id']
            value = i['sub_count']
            sub_exe_count[key] = value
        # print(sub_exe_count)

        # 计算每个承办任务的预计、实际工作量，并插入字典
        for i in main_credit:
            i['main_pre_cal'] = i['main_executor__predict_work'] * i['main_executor__evaluate_factor']
            i['main_real_cal'] = i['main_executor__real_work'] * i['main_executor__evaluate_factor']
            # print(i)
            # print(str(i['sub_executor']))

        # 将协办任务对应的人数插入，计算每个协办任务的预计、实际工作量，并插入字典
        for i in sub_credit:
            sub_todo_id = i['sub_executor']
            i['sub_exe_count'] = sub_exe_count[sub_todo_id]
            i['sub_pre_cal'] = i['sub_executor__predict_work'] * (1 - i['sub_executor__evaluate_factor']) / i['sub_exe_count']
            i['sub_real_cal'] = i['sub_executor__real_work'] * (1 - i['sub_executor__evaluate_factor']) / i['sub_exe_count']
            i['sub_count'] = 1  # 用于帮助累加程序计算每个用户的协办任务数量， sub_exe_count会返回此协办任务的协办人数，在累加时导致计算错误
            # print(i)
            # print(str(i['sub_executor']))

        # 用于按用户名合并任务，会对指定字段进行累加，类似GROUP BY(SUM)，但会丢失无需计算的部分，因此之前需要单独构建姓名字典
        def solve(dataset, group_by_key, sum_value_keys):
            dic = defaultdict(Counter)
            for item in dataset:
                key = item[group_by_key]
                vals = {k: item[k] for k in sum_value_keys}
                dic[key].update(vals)
            return dic
        main_credit = solve(main_credit, 'username', ['main_pre_cal', 'main_real_cal', 'main_count'])
        main_credit = dict(main_credit)
        sub_credit = solve(sub_credit, 'username', ['sub_pre_cal', 'sub_real_cal', 'sub_count'])
        sub_credit = dict(sub_credit)

        # 按用户名合并承办与协办任务字典
        total_credit = deepcopy(main_credit)
        for key in sub_credit.keys():
            if key in total_credit:
                total_credit[key].update(sub_credit[key])
            else:
                total_credit[key] = sub_credit[key]

        # print(total_credit['admin']['sub_pre_cal'])
        # 根据字典内容，计算总工作量
        for key, value in total_credit.items():
            # print(value)
            value['pre_cal'] = value['sub_pre_cal'] + value['main_pre_cal']
            value['real_cal'] = value['sub_real_cal'] + value['main_real_cal']
            value['real_name'] = user_name[key]
        # total_credit = dict(main_credit.items() + sub_credit.items())
        # for value in sub_credit.values():
        #     dict(value)
        # print(sub_credit)
        #
        # new_pair = {}
        # for doc, tab in sub_credit.items():
        #     new_pair[doc] = {}
        #     for word, freq in tab.items():
        #         new_pair[doc][word] = freq
        # print(new_pair)
        # return HttpResponse(str(main_credit)+str(sub_credit))

        # 若total_credit为空，不进行以下操作，避免err
        if total_credit:
            # 暂时解决当该用户当月无任务时，total_credit中不包含该用户的用户名，导致Key Error
            try:
                current_user = total_credit[request.user.username]
            except:
                current_user = {}

            # 累加该部门各个用户的工作量，计算部门工作量
            department_cal = {}
            temp_pre = []
            depart_pre, depart_real, depart_count = 0, 0, 0
            for username, value in total_credit.items():
                print(username)
                print(value['pre_cal'])
                depart_pre = depart_pre + value['pre_cal']
                depart_real = depart_real + value['real_cal']
                depart_count = depart_count + value['main_count']
                temp_pre.append(value['pre_cal'])
                department_cal['pre_cal'] = depart_pre
                department_cal['real_cal'] = depart_real
                department_cal['depart_count'] = depart_count
            department_cal['pre_avg'] = department_cal['pre_cal'] / len(total_credit)
            department_cal['real_avg'] = department_cal['real_cal'] / len(total_credit)
        else:
            department_cal, current_user = {}, {}


        # 计算实际工作量、完成质量
        def cal_method(main_list, sub_list, user_name):
            # print(main_list, sub_list, user_name)

            # sub_credit = sub_list
            # main_credit = main_list

            total_data = []
            season = 1
            # 分别计算每个季度的工作量、评价
            for main_credit, sub_credit in zip(main_list, sub_list):
                # TODO 对于完成质量的核算，先对评价求和，再除以已评价的承办任务数
                # for i in main_credit:
                # print(i['main_executor__quality_mark__mark_value__mark_value'])
                # print(main_credit)
                quality_dict = {}
                for i in main_credit:
                    # 先赋值0，避免前端显示个[]
                    quality_dict[i['username']] = []
                    if i['main_executor__quality_mark__mark_value__mark_value'] != None:
                        quality_dict[i['username']].append(i['main_executor__quality_mark__mark_value__mark_value'])

                # TEST
                for i in sub_credit:
                    # 先赋值0，避免前端显示个[]
                    quality_dict[i['username']] = []
                    if i['sub_executor__quality_mark__mark_value__mark_value'] != None:
                        quality_dict[i['username']].append(i['sub_executor__quality_mark__mark_value__mark_value'])


                for key, value in quality_dict.items():
                    if value:
                        quality_dict[key] = sum(value) / len(value)
                # print(quality_dict)

                main_credit = solve(main_credit, 'username',
                                    ['main_pre_cal', 'main_real_cal', 'main_count', 'main_executor__evaluate_factor'])
                main_credit = dict(main_credit)
                sub_credit = solve(sub_credit, 'username', ['sub_pre_cal', 'sub_real_cal', 'sub_count'])
                sub_credit = dict(sub_credit)

                # 按用户名合并承办与协办任务字典
                total_credit = deepcopy(main_credit)
                for key in sub_credit.keys():
                    if key in total_credit:
                        total_credit[key].update(sub_credit[key])
                    else:
                        total_credit[key] = sub_credit[key]

                # print(total_credit['admin']['sub_pre_cal'])
                # 根据字典内容，计算总工作量
                for key, value in total_credit.items():
                    # print(value)
                    value['pre_cal'] = value['sub_pre_cal'] + value['main_pre_cal']
                    value['real_cal'] = value['sub_real_cal'] + value['main_real_cal']
                    value['real_name'] = user_name[key]
                    value['season'] = season

                    # 由于不计算协办任务，quality_dict会有空值情况
                    try:
                        value['quality'] = quality_dict[key]
                    except:
                        value['quality'] = 0

                for value in total_credit.values():

templates/tasks/group_todolist.html
{% extends 'tasks/base.html' %}

{% block main_content %}

    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-xl">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"> 部门工作事项 <small></small></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'tasks:index' %}">主页</a></li>
              <li class="breadcrumb-item active">工作包</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <div class="content">
      <div class="container-xl">
        <div class="row">
{#        col-lg-6 #}
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title" style="margin: auto" >{{ date }}</h3>

                <div class="card-tools">
                  <ul class="pagination float-right">
                    {% load taskfilter %}
                    <li class="page-item"><a class="page-link" href="/group_todolist/{{ date|last_month }}">«</a></li>
                    <li class="page-item"><a class="page-link"> {{ date|this_month }}月 </a></li>
                    <li class="page-item"><a class="page-link" href="/group_todolist/{{ date|next_month }}">»</a></li>
                  </ul>
                </div>
              </div>
{#                <div class="card-header">#}
{#                  <h3 class="card-title">我的任务</h3>#}
{#                </div>#}
                <!-- /.card-header -->
                <div class="card-body p-0">
{#                  <div class="btn-group">#}
{#                    <button type="button" class="btn btn-default">1</button>#}
{#                    <div class="btn-group">#}
{#                          <button type="button" class="btn btn-default dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">#}
{#                          </button>#}
{#                          <div class="dropdown-menu" style="">#}
{#                            <a class="dropdown-item" href="#">Dropdown link</a>#}
{#                            <a class="dropdown-item" href="#">Dropdown link</a>#}
{#                          </div>#}
{#                    </div>#}
{#                  </div>#}
                  <table class="table" style="word-break: break-all">
                    <thead>
                      <tr>
                        <th style="width: 16px; text-align:center; vertical-align: middle;">序号</th>
                        <th style="width: 280px; text-align:center; vertical-align: middle;">工作事项</th>
                        <th style="width: 100px; text-align:center; vertical-align: middle;">完成时间</th>
                        <th style="width: 160px; text-align:center; vertical-align: middle;">工作要求及交付物</th>
                        <th style="width: 60px; text-align:center; vertical-align: middle;">任务编号</th>
                        <th style="width: 120px; text-align:center; vertical-align: middle;">任务来源</th>
                        <th style="width: 120px; text-align:center; vertical-align: middle;">承办单位</th>
                        <th style="width: 120px;text-align:center; vertical-align: middle;">承/督办人</th>
                        <th style="width: 200px;text-align:center; vertical-align: middle;">协办人</th>
                        <th style="width: 80px; text-align:center; vertical-align: middle;">工作量(pre)</th>
                        <th style="width: 60px; text-align:center; vertical-align: middle;">折算系数</th>
                        <th style="width: 80px; text-align:center; vertical-align: middle;">工作量</th>
                        <th style="width: 100px; text-align:center; vertical-align: middle;">成熟度</th>
                        <th style="width: 220px; text-align:center; vertical-align: middle;">完成情况</th>
                        <th style="width: 120px; text-align:center; vertical-align: middle;">完成质量</th>
{#                        <th style="width: 40px">Label</th>#}
                      </tr>
                    </thead>
                    <tbody>
                      {% for todo in group_todo %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ todo.todo_topic }}</td>
                        <td style="text-align: center">{{ todo.deadline | date:"m月d日" }}</td>
                        <td style="width: 160px"><textarea style="width:100%;overflow:hidden">{{ todo.todo_note }}</textarea></td>
                        <td style="text-align: center">{{ todo.task_id }}</td>
                        <td style="text-align: center">{{ todo.task_origin }}</td>
                        <td style="text-align: center">{{ todo.duty_group }}</td>
                        <td style="text-align: center">{{ todo.main_executor}}</td>
                        <td style="text-align: center">{{ todo.sub_executor.all|join:", " }}</td>
                        <td style="text-align:center;">{{ todo.predict_work }}</td>
                        <td style="text-align:center;">{{ todo.evaluate_factor }}</td>
                        <td style="text-align:center;">{{ todo.real_work|default:'' }}</td>
                        <td >
                          <div class="progress progress-xs">
                            <div class="progress-bar progress-bar-danger" style="width: {{ todo.maturity }}"></div>
                          </div>
                          <span class="badge bg-gradient-blue">{{ todo.maturity }}</span>
                        </td>
                        <td style="text-align: center"><textarea style="overflow:hidden;width:100%;">{{ todo.complete_note }}</textarea></td>
                        <td style="text-align: center">{{ todo.quality_mark|default:'' }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}

templates/tasks/todolist.html
{% extends 'tasks/base.html' %}

{% block main_content %}

    <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-xl">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h3 class="m-0"> 我的工作事项 ({{ date }}) <small></small></h3>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'tasks:index' %}">主页</a></li>
              <li class="breadcrumb-item active">工作包</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <div class="content">
      <div class="container-xl">
        <div class="row">

{#        col-lg-6 #}
          <div class="col-12">
            <div class="card">

              <div class="card-header">
                <div class="card-tools">
                  <ul class="pagination float-right">
                    {% load taskfilter %}
                    <li class="page-item"><a class="page-link" href="/todolist/{{ date|last_month }}">«</a></li>
                    <li class="page-item"><a class="page-link"> {{ date|this_month }}月 </a></li>
                    <li class="page-item"><a class="page-link" href="/todolist/{{ date|next_month }}">»</a></li>
                  </ul>
                </div>
              </div>
{#                <div class="card-header">#}
{#                  <h3 class="card-title">我的任务</h3>#}
{#                </div>#}
                <!-- /.card-header -->
                <div class="card-body p-0">
{#                  <div class="btn-group">#}
{#                    <button type="button" class="btn btn-default">1</button>#}
{#                    <div class="btn-group">#}
{#                          <button type="button" class="btn btn-default dropdown-toggle dropdown-icon" data-toggle="dropdown" aria-expanded="false">#}
{#                          </button>#}
{#                          <div class="dropdown-menu" style="">#}
{#                            <a class="dropdown-item" href="#">Dropdown link</a>#}
{#                            <a class="dropdown-item" href="#">Dropdown link</a>#}
{#                          </div>#}
{#                    </div>#}
{#                  </div>#}
                  <table class="table" style="word-break: break-all">
                    <thead>
                      <br>
                      <h3 style="text-align: center; letter-spacing: 30px">我的承办</h3>
                      <HR  width="50%" color=#e2e4e6 SIZE=3>
                      <tr>
                        <th style="width: 100px; text-align:center; vertical-align: middle;">序号</th>
                        <th style="width: 300px; text-align:center; vertical-align: middle;">工作事项</th>
                        <th style="width: 100px; text-align:center; vertical-align: middle;">完成时间</th>
                        <th style="width: 240px; text-align:center; vertical-align: middle;">工作要求及交付物</th>
                        <th style="width: 140px; text-align:center; vertical-align: middle;">承办单位</th>
                        <th style="width: 200px; text-align:center; vertical-align: middle;">协办人</th>
                        <th style="width: 80px; text-align:center; vertical-align: middle;">工作量(pre)</th>
                        <th style="width: 60px; text-align:center; vertical-align: middle;">折算系数</th>
                        <th style="width: 80px; text-align:center; vertical-align: middle;">工作量</th>
                        <th style="width: 100px; text-align:center; vertical-align: middle;">成熟度</th>
                        <th style="width: 320px; text-align:center; vertical-align: middle;">完成情况</th>
                        <th style="width: 120px; text-align:center; vertical-align: middle;">完成质量</th>
                        <th style="text-align:center; vertical-align: middle;"></th>
{#                        <th style="width: 40px">Label</th>#}
                      </tr>
                    </thead>
                    <tbody>
                      {% for todo in my_todo %}
                      <tr>
                        <td style="text-align: center">{{ forloop.counter }}</td>
                        <td>{{ todo.todo_topic }}</td>
                        <td style="text-align: center">{{ todo.deadline | date:"m月d日" }}</td>
                        <td><textarea style="width:100%;overflow:hidden">{{ todo.todo_note }}</textarea></td>
                        <td style="text-align: center">{{ todo.duty_group }}</td>
                        <td style="text-align: center">{{ todo.sub_executor.all|join:", " }}</td>
                        <td style="text-align:center;">{{ todo.predict_work }}</td>
                        <td style="text-align:center;">{{ todo.evaluate_factor }}</td>
                        <td style="text-align:center;">{{ todo.real_work|default:'' }}</td>
                        <td >
                          <div class="progress progress-xs">
                            <div class="progress-bar progress-bar-danger" style="width: {{ todo.maturity }}"></div>
                          </div>
                          <span class="badge bg-gradient-blue">{{ todo.maturity }}</span>
                        </td>
                        <td style="text-align: center"><textarea style="overflow:hidden; width: 100%" readonly="readonly">{{ todo.complete_note }}</textarea></td>
                        <td style="text-align: center">{{ todo.quality_mark|default:'' }}</td>
                        <td><a href="{% url 'tasks:todo_detail' pk=todo.id %}?next={{ current_path }}">填报</a> </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
                <div class="card-body p-0">
                  <table class="table" style="word-break: break-all">
                    <thead>
                      <HR  width="100%" color=#e2e4e6 SIZE=9>
                      </br>
                      <h3 style="text-align: center; letter-spacing: 30px">我的协办</h3>
                      <HR  width="50%" color=#e2e4e6 SIZE=3>
                      <tr>
                        <th style="width: 70px; text-align:center; vertical-align: middle;">序号</th>
                        <th style="width: 300px; text-align:center; vertical-align: middle;">工作事项</th>
                        <th style="width: 100px; text-align:center; vertical-align: middle;">完成时间</th>
                        <th style="width: 240px; text-align:center; vertical-align: middle;">工作要求及交付物</th>
                        <th style="width: 140px; text-align:center; vertical-align: middle;">承办单位</th>
                        <th style="width: 200px;text-align:center; vertical-align: middle;">承/督办人</th>
{#                        <th style="width: 200px;text-align:center; vertical-align: middle;">协办人</th>#}
                        <th style="width: 80px; text-align:center; vertical-align: middle;">工作量(pre)</th>
                        <th style="width: 60px; text-align:center; vertical-align: middle;">折算系数</th>
                        <th style="width: 80px; text-align:center; vertical-align: middle;">工作量</th>
                        <th style="width: 100px; text-align:center; vertical-align: middle;">成熟度</th>
                        <th style="width: 320px; text-align:center; vertical-align: middle;">完成情况</th>
                        <th style="width: 120px; text-align:center; vertical-align: middle;">完成质量</th>
                        <th style="text-align:center; vertical-align: middle;"></th>
{#                        <th style="width: 40px">Label</th>#}
                      </tr>
                    </thead>
                    <tbody>
                      {% for todo in my_sub_todo %}
                      <tr>
                        <td style="text-align: center">{{ forloop.counter }}</td>
                        <td>{{ todo.todo_topic }}</td>
                        <td style="text-align: center">{{ todo.deadline | date:"m月d日" }}</td>
                        <td><textarea style="width:100%;overflow:hidden">{{ todo.todo_note }}</textarea></td>
                        <td style="text-align: center">{{ todo.duty_group }}</td>
                        <td style="text-align: center">{{ todo.main_executor }}</td>
{#                        <td style="text-align: center">{{ todo.sub_executor.all|join:", " }}</td>#}
                        <td style="text-align:center;">{{ todo.predict_work }}</td>
                        <td style="text-align:center;">{{ todo.evaluate_factor }}</td>
                        <td style="text-align:center;">{{ todo.real_work|default:'' }}</td>
                        <td >
                          <div class="progress progress-xs">
                            <div class="progress-bar progress-bar-danger" style="width: {{ todo.maturity }}"></div>
                          </div>
                          <span class="badge bg-gradient-blue">{{ todo.maturity }}</span>
                        </td>
                        <td style="text-align: center"><textarea style="overflow:hidden; width:100%" readonly="readonly">{{ todo.complete_note }}</textarea></td>
                        <td style="text-align: center">{{ todo.quality_mark|default:'' }}</td>
                        <td><a href="{% url 'tasks:todo_detail' pk=todo.id %}?next={{ current_path }}">填报</a> </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
{% endblock %}